// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

/**
 * Protobuf type {@code org.gbif.vocabulary.grpc.Concept}
 */
public  final class Concept extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.gbif.vocabulary.grpc.Concept)
    ConceptOrBuilder {
  // Use Concept.newBuilder() to construct.
  private Concept(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Concept() {
    vocabularyKey_ = 0;
    parentKey_ = 0;
    replacedByKey_ = 0;
    name_ = "";
    externalDefinitionUrl_ = "";
    sameAsUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    editorialNotes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    createdBy_ = "";
    modifiedBy_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Concept(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            vocabularyKey_ = input.readInt32();
            break;
          }
          case 16: {

            parentKey_ = input.readInt32();
            break;
          }
          case 24: {

            replacedByKey_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              label_ = com.google.protobuf.MapField.newMapField(
                  LabelDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            label__ = input.readMessage(
                LabelDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            label_.getMutableMap().put(
                label__.getKey(), label__.getValue());
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              alternativeLabel_ = com.google.protobuf.MapField.newMapField(
                  AlternativeLabelDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000020;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            alternativeLabel__ = input.readMessage(
                AlternativeLabelDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            alternativeLabel_.getMutableMap().put(
                alternativeLabel__.getKey(), alternativeLabel__.getValue());
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              definition_ = com.google.protobuf.MapField.newMapField(
                  DefinitionDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000040;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            definition__ = input.readMessage(
                DefinitionDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            definition_.getMutableMap().put(
                definition__.getKey(), definition__.getValue());
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            externalDefinitionUrl_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              sameAsUrl_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            sameAsUrl_.add(s);
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              editorialNotes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000200;
            }
            editorialNotes_.add(s);
            break;
          }
          case 90: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (created_ != null) {
              subBuilder = created_.toBuilder();
            }
            created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(created_);
              created_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            createdBy_ = s;
            break;
          }
          case 106: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (modified_ != null) {
              subBuilder = modified_.toBuilder();
            }
            modified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modified_);
              modified_ = subBuilder.buildPartial();
            }

            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            modifiedBy_ = s;
            break;
          }
          case 122: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (deleted_ != null) {
              subBuilder = deleted_.toBuilder();
            }
            deleted_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deleted_);
              deleted_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        sameAsUrl_ = sameAsUrl_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        editorialNotes_ = editorialNotes_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetLabel();
      case 6:
        return internalGetAlternativeLabel();
      case 7:
        return internalGetDefinition();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gbif.vocabulary.grpc.Concept.class, org.gbif.vocabulary.grpc.Concept.Builder.class);
  }

  private int bitField0_;
  public static final int VOCABULARY_KEY_FIELD_NUMBER = 1;
  private int vocabularyKey_;
  /**
   * <code>int32 vocabulary_key = 1;</code>
   */
  public int getVocabularyKey() {
    return vocabularyKey_;
  }

  public static final int PARENT_KEY_FIELD_NUMBER = 2;
  private int parentKey_;
  /**
   * <code>int32 parent_key = 2;</code>
   */
  public int getParentKey() {
    return parentKey_;
  }

  public static final int REPLACED_BY_KEY_FIELD_NUMBER = 3;
  private int replacedByKey_;
  /**
   * <code>int32 replaced_by_key = 3;</code>
   */
  public int getReplacedByKey() {
    return replacedByKey_;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 4;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 5;
  private static final class LabelDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> label_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetLabel() {
    if (label_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          LabelDefaultEntryHolder.defaultEntry);
    }
    return label_;
  }

  public int getLabelCount() {
    return internalGetLabel().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  public boolean containsLabel(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetLabel().getMap().containsKey(key);
  }
  /**
   * Use {@link #getLabelMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getLabel() {
    return getLabelMap();
  }
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getLabelMap() {
    return internalGetLabel().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  public java.lang.String getLabelOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetLabel().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  public java.lang.String getLabelOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetLabel().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ALTERNATIVE_LABEL_FIELD_NUMBER = 6;
  private static final class AlternativeLabelDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> alternativeLabel_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAlternativeLabel() {
    if (alternativeLabel_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AlternativeLabelDefaultEntryHolder.defaultEntry);
    }
    return alternativeLabel_;
  }

  public int getAlternativeLabelCount() {
    return internalGetAlternativeLabel().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  public boolean containsAlternativeLabel(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAlternativeLabel().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAlternativeLabelMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAlternativeLabel() {
    return getAlternativeLabelMap();
  }
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getAlternativeLabelMap() {
    return internalGetAlternativeLabel().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  public java.lang.String getAlternativeLabelOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAlternativeLabel().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  public java.lang.String getAlternativeLabelOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAlternativeLabel().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int DEFINITION_FIELD_NUMBER = 7;
  private static final class DefinitionDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> definition_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetDefinition() {
    if (definition_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DefinitionDefaultEntryHolder.defaultEntry);
    }
    return definition_;
  }

  public int getDefinitionCount() {
    return internalGetDefinition().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  public boolean containsDefinition(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetDefinition().getMap().containsKey(key);
  }
  /**
   * Use {@link #getDefinitionMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getDefinition() {
    return getDefinitionMap();
  }
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getDefinitionMap() {
    return internalGetDefinition().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  public java.lang.String getDefinitionOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDefinition().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  public java.lang.String getDefinitionOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetDefinition().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int EXTERNAL_DEFINITION_URL_FIELD_NUMBER = 8;
  private volatile java.lang.Object externalDefinitionUrl_;
  /**
   * <code>string external_definition_url = 8;</code>
   */
  public java.lang.String getExternalDefinitionUrl() {
    java.lang.Object ref = externalDefinitionUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalDefinitionUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string external_definition_url = 8;</code>
   */
  public com.google.protobuf.ByteString
      getExternalDefinitionUrlBytes() {
    java.lang.Object ref = externalDefinitionUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalDefinitionUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAME_AS_URL_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList sameAsUrl_;
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getSameAsUrlList() {
    return sameAsUrl_;
  }
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  public int getSameAsUrlCount() {
    return sameAsUrl_.size();
  }
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  public java.lang.String getSameAsUrl(int index) {
    return sameAsUrl_.get(index);
  }
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  public com.google.protobuf.ByteString
      getSameAsUrlBytes(int index) {
    return sameAsUrl_.getByteString(index);
  }

  public static final int EDITORIAL_NOTES_FIELD_NUMBER = 10;
  private com.google.protobuf.LazyStringList editorialNotes_;
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getEditorialNotesList() {
    return editorialNotes_;
  }
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  public int getEditorialNotesCount() {
    return editorialNotes_.size();
  }
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  public java.lang.String getEditorialNotes(int index) {
    return editorialNotes_.get(index);
  }
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  public com.google.protobuf.ByteString
      getEditorialNotesBytes(int index) {
    return editorialNotes_.getByteString(index);
  }

  public static final int CREATED_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp created_;
  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  public boolean hasCreated() {
    return created_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return getCreated();
  }

  public static final int CREATED_BY_FIELD_NUMBER = 12;
  private volatile java.lang.Object createdBy_;
  /**
   * <code>string created_by = 12;</code>
   */
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string created_by = 12;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODIFIED_FIELD_NUMBER = 13;
  private com.google.protobuf.Timestamp modified_;
  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  public boolean hasModified() {
    return modified_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  public com.google.protobuf.Timestamp getModified() {
    return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
    return getModified();
  }

  public static final int MODIFIED_BY_FIELD_NUMBER = 14;
  private volatile java.lang.Object modifiedBy_;
  /**
   * <code>string modified_by = 14;</code>
   */
  public java.lang.String getModifiedBy() {
    java.lang.Object ref = modifiedBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modifiedBy_ = s;
      return s;
    }
  }
  /**
   * <code>string modified_by = 14;</code>
   */
  public com.google.protobuf.ByteString
      getModifiedByBytes() {
    java.lang.Object ref = modifiedBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modifiedBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELETED_FIELD_NUMBER = 15;
  private com.google.protobuf.Timestamp deleted_;
  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  public boolean hasDeleted() {
    return deleted_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  public com.google.protobuf.Timestamp getDeleted() {
    return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
  }
  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
    return getDeleted();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (vocabularyKey_ != 0) {
      output.writeInt32(1, vocabularyKey_);
    }
    if (parentKey_ != 0) {
      output.writeInt32(2, parentKey_);
    }
    if (replacedByKey_ != 0) {
      output.writeInt32(3, replacedByKey_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetLabel(),
        LabelDefaultEntryHolder.defaultEntry,
        5);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAlternativeLabel(),
        AlternativeLabelDefaultEntryHolder.defaultEntry,
        6);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetDefinition(),
        DefinitionDefaultEntryHolder.defaultEntry,
        7);
    if (!getExternalDefinitionUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, externalDefinitionUrl_);
    }
    for (int i = 0; i < sameAsUrl_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sameAsUrl_.getRaw(i));
    }
    for (int i = 0; i < editorialNotes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, editorialNotes_.getRaw(i));
    }
    if (created_ != null) {
      output.writeMessage(11, getCreated());
    }
    if (!getCreatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, createdBy_);
    }
    if (modified_ != null) {
      output.writeMessage(13, getModified());
    }
    if (!getModifiedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, modifiedBy_);
    }
    if (deleted_ != null) {
      output.writeMessage(15, getDeleted());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (vocabularyKey_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, vocabularyKey_);
    }
    if (parentKey_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, parentKey_);
    }
    if (replacedByKey_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, replacedByKey_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetLabel().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      label__ = LabelDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, label__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAlternativeLabel().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      alternativeLabel__ = AlternativeLabelDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, alternativeLabel__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetDefinition().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      definition__ = DefinitionDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, definition__);
    }
    if (!getExternalDefinitionUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, externalDefinitionUrl_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sameAsUrl_.size(); i++) {
        dataSize += computeStringSizeNoTag(sameAsUrl_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSameAsUrlList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < editorialNotes_.size(); i++) {
        dataSize += computeStringSizeNoTag(editorialNotes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEditorialNotesList().size();
    }
    if (created_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCreated());
    }
    if (!getCreatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, createdBy_);
    }
    if (modified_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getModified());
    }
    if (!getModifiedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, modifiedBy_);
    }
    if (deleted_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getDeleted());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gbif.vocabulary.grpc.Concept)) {
      return super.equals(obj);
    }
    org.gbif.vocabulary.grpc.Concept other = (org.gbif.vocabulary.grpc.Concept) obj;

    boolean result = true;
    result = result && (getVocabularyKey()
        == other.getVocabularyKey());
    result = result && (getParentKey()
        == other.getParentKey());
    result = result && (getReplacedByKey()
        == other.getReplacedByKey());
    result = result && getName()
        .equals(other.getName());
    result = result && internalGetLabel().equals(
        other.internalGetLabel());
    result = result && internalGetAlternativeLabel().equals(
        other.internalGetAlternativeLabel());
    result = result && internalGetDefinition().equals(
        other.internalGetDefinition());
    result = result && getExternalDefinitionUrl()
        .equals(other.getExternalDefinitionUrl());
    result = result && getSameAsUrlList()
        .equals(other.getSameAsUrlList());
    result = result && getEditorialNotesList()
        .equals(other.getEditorialNotesList());
    result = result && (hasCreated() == other.hasCreated());
    if (hasCreated()) {
      result = result && getCreated()
          .equals(other.getCreated());
    }
    result = result && getCreatedBy()
        .equals(other.getCreatedBy());
    result = result && (hasModified() == other.hasModified());
    if (hasModified()) {
      result = result && getModified()
          .equals(other.getModified());
    }
    result = result && getModifiedBy()
        .equals(other.getModifiedBy());
    result = result && (hasDeleted() == other.hasDeleted());
    if (hasDeleted()) {
      result = result && getDeleted()
          .equals(other.getDeleted());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VOCABULARY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getVocabularyKey();
    hash = (37 * hash) + PARENT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getParentKey();
    hash = (37 * hash) + REPLACED_BY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getReplacedByKey();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (!internalGetLabel().getMap().isEmpty()) {
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + internalGetLabel().hashCode();
    }
    if (!internalGetAlternativeLabel().getMap().isEmpty()) {
      hash = (37 * hash) + ALTERNATIVE_LABEL_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAlternativeLabel().hashCode();
    }
    if (!internalGetDefinition().getMap().isEmpty()) {
      hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDefinition().hashCode();
    }
    hash = (37 * hash) + EXTERNAL_DEFINITION_URL_FIELD_NUMBER;
    hash = (53 * hash) + getExternalDefinitionUrl().hashCode();
    if (getSameAsUrlCount() > 0) {
      hash = (37 * hash) + SAME_AS_URL_FIELD_NUMBER;
      hash = (53 * hash) + getSameAsUrlList().hashCode();
    }
    if (getEditorialNotesCount() > 0) {
      hash = (37 * hash) + EDITORIAL_NOTES_FIELD_NUMBER;
      hash = (53 * hash) + getEditorialNotesList().hashCode();
    }
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    hash = (37 * hash) + CREATED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    if (hasModified()) {
      hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getModified().hashCode();
    }
    hash = (37 * hash) + MODIFIED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getModifiedBy().hashCode();
    if (hasDeleted()) {
      hash = (37 * hash) + DELETED_FIELD_NUMBER;
      hash = (53 * hash) + getDeleted().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Concept parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Concept parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Concept parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gbif.vocabulary.grpc.Concept prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.gbif.vocabulary.grpc.Concept}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.gbif.vocabulary.grpc.Concept)
      org.gbif.vocabulary.grpc.ConceptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetLabel();
        case 6:
          return internalGetAlternativeLabel();
        case 7:
          return internalGetDefinition();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableLabel();
        case 6:
          return internalGetMutableAlternativeLabel();
        case 7:
          return internalGetMutableDefinition();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gbif.vocabulary.grpc.Concept.class, org.gbif.vocabulary.grpc.Concept.Builder.class);
    }

    // Construct using org.gbif.vocabulary.grpc.Concept.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      vocabularyKey_ = 0;

      parentKey_ = 0;

      replacedByKey_ = 0;

      name_ = "";

      internalGetMutableLabel().clear();
      internalGetMutableAlternativeLabel().clear();
      internalGetMutableDefinition().clear();
      externalDefinitionUrl_ = "";

      sameAsUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      editorialNotes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000200);
      if (createdBuilder_ == null) {
        created_ = null;
      } else {
        created_ = null;
        createdBuilder_ = null;
      }
      createdBy_ = "";

      if (modifiedBuilder_ == null) {
        modified_ = null;
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }
      modifiedBy_ = "";

      if (deletedBuilder_ == null) {
        deleted_ = null;
      } else {
        deleted_ = null;
        deletedBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Concept_descriptor;
    }

    public org.gbif.vocabulary.grpc.Concept getDefaultInstanceForType() {
      return org.gbif.vocabulary.grpc.Concept.getDefaultInstance();
    }

    public org.gbif.vocabulary.grpc.Concept build() {
      org.gbif.vocabulary.grpc.Concept result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.gbif.vocabulary.grpc.Concept buildPartial() {
      org.gbif.vocabulary.grpc.Concept result = new org.gbif.vocabulary.grpc.Concept(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.vocabularyKey_ = vocabularyKey_;
      result.parentKey_ = parentKey_;
      result.replacedByKey_ = replacedByKey_;
      result.name_ = name_;
      result.label_ = internalGetLabel();
      result.label_.makeImmutable();
      result.alternativeLabel_ = internalGetAlternativeLabel();
      result.alternativeLabel_.makeImmutable();
      result.definition_ = internalGetDefinition();
      result.definition_.makeImmutable();
      result.externalDefinitionUrl_ = externalDefinitionUrl_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        sameAsUrl_ = sameAsUrl_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.sameAsUrl_ = sameAsUrl_;
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        editorialNotes_ = editorialNotes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000200);
      }
      result.editorialNotes_ = editorialNotes_;
      if (createdBuilder_ == null) {
        result.created_ = created_;
      } else {
        result.created_ = createdBuilder_.build();
      }
      result.createdBy_ = createdBy_;
      if (modifiedBuilder_ == null) {
        result.modified_ = modified_;
      } else {
        result.modified_ = modifiedBuilder_.build();
      }
      result.modifiedBy_ = modifiedBy_;
      if (deletedBuilder_ == null) {
        result.deleted_ = deleted_;
      } else {
        result.deleted_ = deletedBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gbif.vocabulary.grpc.Concept) {
        return mergeFrom((org.gbif.vocabulary.grpc.Concept)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gbif.vocabulary.grpc.Concept other) {
      if (other == org.gbif.vocabulary.grpc.Concept.getDefaultInstance()) return this;
      if (other.getVocabularyKey() != 0) {
        setVocabularyKey(other.getVocabularyKey());
      }
      if (other.getParentKey() != 0) {
        setParentKey(other.getParentKey());
      }
      if (other.getReplacedByKey() != 0) {
        setReplacedByKey(other.getReplacedByKey());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      internalGetMutableLabel().mergeFrom(
          other.internalGetLabel());
      internalGetMutableAlternativeLabel().mergeFrom(
          other.internalGetAlternativeLabel());
      internalGetMutableDefinition().mergeFrom(
          other.internalGetDefinition());
      if (!other.getExternalDefinitionUrl().isEmpty()) {
        externalDefinitionUrl_ = other.externalDefinitionUrl_;
        onChanged();
      }
      if (!other.sameAsUrl_.isEmpty()) {
        if (sameAsUrl_.isEmpty()) {
          sameAsUrl_ = other.sameAsUrl_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureSameAsUrlIsMutable();
          sameAsUrl_.addAll(other.sameAsUrl_);
        }
        onChanged();
      }
      if (!other.editorialNotes_.isEmpty()) {
        if (editorialNotes_.isEmpty()) {
          editorialNotes_ = other.editorialNotes_;
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          ensureEditorialNotesIsMutable();
          editorialNotes_.addAll(other.editorialNotes_);
        }
        onChanged();
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        onChanged();
      }
      if (other.hasModified()) {
        mergeModified(other.getModified());
      }
      if (!other.getModifiedBy().isEmpty()) {
        modifiedBy_ = other.modifiedBy_;
        onChanged();
      }
      if (other.hasDeleted()) {
        mergeDeleted(other.getDeleted());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.gbif.vocabulary.grpc.Concept parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.gbif.vocabulary.grpc.Concept) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int vocabularyKey_ ;
    /**
     * <code>int32 vocabulary_key = 1;</code>
     */
    public int getVocabularyKey() {
      return vocabularyKey_;
    }
    /**
     * <code>int32 vocabulary_key = 1;</code>
     */
    public Builder setVocabularyKey(int value) {
      
      vocabularyKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 vocabulary_key = 1;</code>
     */
    public Builder clearVocabularyKey() {
      
      vocabularyKey_ = 0;
      onChanged();
      return this;
    }

    private int parentKey_ ;
    /**
     * <code>int32 parent_key = 2;</code>
     */
    public int getParentKey() {
      return parentKey_;
    }
    /**
     * <code>int32 parent_key = 2;</code>
     */
    public Builder setParentKey(int value) {
      
      parentKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 parent_key = 2;</code>
     */
    public Builder clearParentKey() {
      
      parentKey_ = 0;
      onChanged();
      return this;
    }

    private int replacedByKey_ ;
    /**
     * <code>int32 replaced_by_key = 3;</code>
     */
    public int getReplacedByKey() {
      return replacedByKey_;
    }
    /**
     * <code>int32 replaced_by_key = 3;</code>
     */
    public Builder setReplacedByKey(int value) {
      
      replacedByKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 replaced_by_key = 3;</code>
     */
    public Builder clearReplacedByKey() {
      
      replacedByKey_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> label_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetLabel() {
      if (label_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LabelDefaultEntryHolder.defaultEntry);
      }
      return label_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableLabel() {
      onChanged();;
      if (label_ == null) {
        label_ = com.google.protobuf.MapField.newMapField(
            LabelDefaultEntryHolder.defaultEntry);
      }
      if (!label_.isMutable()) {
        label_ = label_.copy();
      }
      return label_;
    }

    public int getLabelCount() {
      return internalGetLabel().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public boolean containsLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetLabel().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLabelMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getLabel() {
      return getLabelMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getLabelMap() {
      return internalGetLabel().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public java.lang.String getLabelOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabel().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public java.lang.String getLabelOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetLabel().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearLabel() {
      internalGetMutableLabel().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public Builder removeLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableLabel().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableLabel() {
      return internalGetMutableLabel().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */
    public Builder putLabel(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableLabel().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; label = 5;</code>
     */

    public Builder putAllLabel(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableLabel().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> alternativeLabel_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAlternativeLabel() {
      if (alternativeLabel_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AlternativeLabelDefaultEntryHolder.defaultEntry);
      }
      return alternativeLabel_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAlternativeLabel() {
      onChanged();;
      if (alternativeLabel_ == null) {
        alternativeLabel_ = com.google.protobuf.MapField.newMapField(
            AlternativeLabelDefaultEntryHolder.defaultEntry);
      }
      if (!alternativeLabel_.isMutable()) {
        alternativeLabel_ = alternativeLabel_.copy();
      }
      return alternativeLabel_;
    }

    public int getAlternativeLabelCount() {
      return internalGetAlternativeLabel().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public boolean containsAlternativeLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAlternativeLabel().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAlternativeLabelMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAlternativeLabel() {
      return getAlternativeLabelMap();
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAlternativeLabelMap() {
      return internalGetAlternativeLabel().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public java.lang.String getAlternativeLabelOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAlternativeLabel().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public java.lang.String getAlternativeLabelOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAlternativeLabel().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAlternativeLabel() {
      internalGetMutableAlternativeLabel().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public Builder removeAlternativeLabel(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAlternativeLabel().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAlternativeLabel() {
      return internalGetMutableAlternativeLabel().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */
    public Builder putAlternativeLabel(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAlternativeLabel().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; alternative_label = 6;</code>
     */

    public Builder putAllAlternativeLabel(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAlternativeLabel().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> definition_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetDefinition() {
      if (definition_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DefinitionDefaultEntryHolder.defaultEntry);
      }
      return definition_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableDefinition() {
      onChanged();;
      if (definition_ == null) {
        definition_ = com.google.protobuf.MapField.newMapField(
            DefinitionDefaultEntryHolder.defaultEntry);
      }
      if (!definition_.isMutable()) {
        definition_ = definition_.copy();
      }
      return definition_;
    }

    public int getDefinitionCount() {
      return internalGetDefinition().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public boolean containsDefinition(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetDefinition().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDefinitionMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDefinition() {
      return getDefinitionMap();
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getDefinitionMap() {
      return internalGetDefinition().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public java.lang.String getDefinitionOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDefinition().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public java.lang.String getDefinitionOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetDefinition().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearDefinition() {
      internalGetMutableDefinition().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public Builder removeDefinition(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableDefinition().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableDefinition() {
      return internalGetMutableDefinition().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */
    public Builder putDefinition(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableDefinition().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; definition = 7;</code>
     */

    public Builder putAllDefinition(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableDefinition().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object externalDefinitionUrl_ = "";
    /**
     * <code>string external_definition_url = 8;</code>
     */
    public java.lang.String getExternalDefinitionUrl() {
      java.lang.Object ref = externalDefinitionUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalDefinitionUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string external_definition_url = 8;</code>
     */
    public com.google.protobuf.ByteString
        getExternalDefinitionUrlBytes() {
      java.lang.Object ref = externalDefinitionUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalDefinitionUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string external_definition_url = 8;</code>
     */
    public Builder setExternalDefinitionUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      externalDefinitionUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string external_definition_url = 8;</code>
     */
    public Builder clearExternalDefinitionUrl() {
      
      externalDefinitionUrl_ = getDefaultInstance().getExternalDefinitionUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string external_definition_url = 8;</code>
     */
    public Builder setExternalDefinitionUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      externalDefinitionUrl_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList sameAsUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSameAsUrlIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        sameAsUrl_ = new com.google.protobuf.LazyStringArrayList(sameAsUrl_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSameAsUrlList() {
      return sameAsUrl_.getUnmodifiableView();
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public int getSameAsUrlCount() {
      return sameAsUrl_.size();
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public java.lang.String getSameAsUrl(int index) {
      return sameAsUrl_.get(index);
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSameAsUrlBytes(int index) {
      return sameAsUrl_.getByteString(index);
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public Builder setSameAsUrl(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSameAsUrlIsMutable();
      sameAsUrl_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public Builder addSameAsUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSameAsUrlIsMutable();
      sameAsUrl_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public Builder addAllSameAsUrl(
        java.lang.Iterable<java.lang.String> values) {
      ensureSameAsUrlIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sameAsUrl_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public Builder clearSameAsUrl() {
      sameAsUrl_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string same_as_url = 9;</code>
     */
    public Builder addSameAsUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSameAsUrlIsMutable();
      sameAsUrl_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList editorialNotes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureEditorialNotesIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        editorialNotes_ = new com.google.protobuf.LazyStringArrayList(editorialNotes_);
        bitField0_ |= 0x00000200;
       }
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getEditorialNotesList() {
      return editorialNotes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public int getEditorialNotesCount() {
      return editorialNotes_.size();
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public java.lang.String getEditorialNotes(int index) {
      return editorialNotes_.get(index);
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public com.google.protobuf.ByteString
        getEditorialNotesBytes(int index) {
      return editorialNotes_.getByteString(index);
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public Builder setEditorialNotes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEditorialNotesIsMutable();
      editorialNotes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public Builder addEditorialNotes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureEditorialNotesIsMutable();
      editorialNotes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public Builder addAllEditorialNotes(
        java.lang.Iterable<java.lang.String> values) {
      ensureEditorialNotesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, editorialNotes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public Builder clearEditorialNotes() {
      editorialNotes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string editorial_notes = 10;</code>
     */
    public Builder addEditorialNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureEditorialNotesIsMutable();
      editorialNotes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp created_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public boolean hasCreated() {
      return createdBuilder_ != null || created_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
        onChanged();
      } else {
        createdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
        onChanged();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (created_ != null) {
          created_ =
            com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
        } else {
          created_ = value;
        }
        onChanged();
      } else {
        createdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public Builder clearCreated() {
      if (createdBuilder_ == null) {
        created_ = null;
        onChanged();
      } else {
        created_ = null;
        createdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string created_by = 12;</code>
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_by = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_by = 12;</code>
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 12;</code>
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 12;</code>
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp modified_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public boolean hasModified() {
      return modifiedBuilder_ != null || modified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public com.google.protobuf.Timestamp getModified() {
      if (modifiedBuilder_ == null) {
        return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      } else {
        return modifiedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public Builder setModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modified_ = value;
        onChanged();
      } else {
        modifiedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public Builder setModified(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedBuilder_ == null) {
        modified_ = builderForValue.build();
        onChanged();
      } else {
        modifiedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public Builder mergeModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (modified_ != null) {
          modified_ =
            com.google.protobuf.Timestamp.newBuilder(modified_).mergeFrom(value).buildPartial();
        } else {
          modified_ = value;
        }
        onChanged();
      } else {
        modifiedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public Builder clearModified() {
      if (modifiedBuilder_ == null) {
        modified_ = null;
        onChanged();
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public com.google.protobuf.Timestamp.Builder getModifiedBuilder() {
      
      onChanged();
      return getModifiedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
      if (modifiedBuilder_ != null) {
        return modifiedBuilder_.getMessageOrBuilder();
      } else {
        return modified_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getModifiedFieldBuilder() {
      if (modifiedBuilder_ == null) {
        modifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getModified(),
                getParentForChildren(),
                isClean());
        modified_ = null;
      }
      return modifiedBuilder_;
    }

    private java.lang.Object modifiedBy_ = "";
    /**
     * <code>string modified_by = 14;</code>
     */
    public java.lang.String getModifiedBy() {
      java.lang.Object ref = modifiedBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modifiedBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modified_by = 14;</code>
     */
    public com.google.protobuf.ByteString
        getModifiedByBytes() {
      java.lang.Object ref = modifiedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifiedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modified_by = 14;</code>
     */
    public Builder setModifiedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modifiedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string modified_by = 14;</code>
     */
    public Builder clearModifiedBy() {
      
      modifiedBy_ = getDefaultInstance().getModifiedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string modified_by = 14;</code>
     */
    public Builder setModifiedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modifiedBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp deleted_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public boolean hasDeleted() {
      return deletedBuilder_ != null || deleted_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public com.google.protobuf.Timestamp getDeleted() {
      if (deletedBuilder_ == null) {
        return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
      } else {
        return deletedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public Builder setDeleted(com.google.protobuf.Timestamp value) {
      if (deletedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deleted_ = value;
        onChanged();
      } else {
        deletedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public Builder setDeleted(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deletedBuilder_ == null) {
        deleted_ = builderForValue.build();
        onChanged();
      } else {
        deletedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public Builder mergeDeleted(com.google.protobuf.Timestamp value) {
      if (deletedBuilder_ == null) {
        if (deleted_ != null) {
          deleted_ =
            com.google.protobuf.Timestamp.newBuilder(deleted_).mergeFrom(value).buildPartial();
        } else {
          deleted_ = value;
        }
        onChanged();
      } else {
        deletedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public Builder clearDeleted() {
      if (deletedBuilder_ == null) {
        deleted_ = null;
        onChanged();
      } else {
        deleted_ = null;
        deletedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeletedBuilder() {
      
      onChanged();
      return getDeletedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
      if (deletedBuilder_ != null) {
        return deletedBuilder_.getMessageOrBuilder();
      } else {
        return deleted_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDeletedFieldBuilder() {
      if (deletedBuilder_ == null) {
        deletedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeleted(),
                getParentForChildren(),
                isClean());
        deleted_ = null;
      }
      return deletedBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.gbif.vocabulary.grpc.Concept)
  }

  // @@protoc_insertion_point(class_scope:org.gbif.vocabulary.grpc.Concept)
  private static final org.gbif.vocabulary.grpc.Concept DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gbif.vocabulary.grpc.Concept();
  }

  public static org.gbif.vocabulary.grpc.Concept getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Concept>
      PARSER = new com.google.protobuf.AbstractParser<Concept>() {
    public Concept parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Concept(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Concept> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Concept> getParserForType() {
    return PARSER;
  }

  public org.gbif.vocabulary.grpc.Concept getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

