// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

public interface ConceptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.gbif.vocabulary.grpc.Concept)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 vocabulary_key = 1;</code>
   */
  int getVocabularyKey();

  /**
   * <code>int32 parent_key = 2;</code>
   */
  int getParentKey();

  /**
   * <code>int32 replaced_by_key = 3;</code>
   */
  int getReplacedByKey();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */
  int getLabelCount();
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */
  boolean containsLabel(
      java.lang.String key);
  /**
   * Use {@link #getLabelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getLabel();
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getLabelMap();
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  java.lang.String getLabelOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; label = 5;</code>
   */

  java.lang.String getLabelOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */
  int getAlternativeLabelCount();
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */
  boolean containsAlternativeLabel(
      java.lang.String key);
  /**
   * Use {@link #getAlternativeLabelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAlternativeLabel();
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAlternativeLabelMap();
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  java.lang.String getAlternativeLabelOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; alternative_label = 6;</code>
   */

  java.lang.String getAlternativeLabelOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */
  int getDefinitionCount();
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */
  boolean containsDefinition(
      java.lang.String key);
  /**
   * Use {@link #getDefinitionMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getDefinition();
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getDefinitionMap();
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  java.lang.String getDefinitionOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; definition = 7;</code>
   */

  java.lang.String getDefinitionOrThrow(
      java.lang.String key);

  /**
   * <code>string external_definition_url = 8;</code>
   */
  java.lang.String getExternalDefinitionUrl();
  /**
   * <code>string external_definition_url = 8;</code>
   */
  com.google.protobuf.ByteString
      getExternalDefinitionUrlBytes();

  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  java.util.List<java.lang.String>
      getSameAsUrlList();
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  int getSameAsUrlCount();
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  java.lang.String getSameAsUrl(int index);
  /**
   * <code>repeated string same_as_url = 9;</code>
   */
  com.google.protobuf.ByteString
      getSameAsUrlBytes(int index);

  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  java.util.List<java.lang.String>
      getEditorialNotesList();
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  int getEditorialNotesCount();
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  java.lang.String getEditorialNotes(int index);
  /**
   * <code>repeated string editorial_notes = 10;</code>
   */
  com.google.protobuf.ByteString
      getEditorialNotesBytes(int index);

  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  boolean hasCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  com.google.protobuf.Timestamp getCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();

  /**
   * <code>string created_by = 12;</code>
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string created_by = 12;</code>
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  boolean hasModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  com.google.protobuf.Timestamp getModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 13;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder();

  /**
   * <code>string modified_by = 14;</code>
   */
  java.lang.String getModifiedBy();
  /**
   * <code>string modified_by = 14;</code>
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();

  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  boolean hasDeleted();
  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  com.google.protobuf.Timestamp getDeleted();
  /**
   * <code>.google.protobuf.Timestamp deleted = 15;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder();
}
