// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

public interface VocabularyKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.gbif.vocabulary.grpc.VocabularyKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 key = 1;</code>
   */
  int getKey();
}
