// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

/**
 * Protobuf type {@code org.gbif.vocabulary.grpc.Vocabulary}
 */
public  final class Vocabulary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.gbif.vocabulary.grpc.Vocabulary)
    VocabularyOrBuilder {
  // Use Vocabulary.newBuilder() to construct.
  private Vocabulary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Vocabulary() {
    key_ = 0;
    namespace_ = "";
    name_ = "";
    label_ = "";
    definition_ = "";
    externalDefinitionUrl_ = "";
    editorialNotes_ = "";
    createdBy_ = "";
    modifiedBy_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Vocabulary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            key_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            namespace_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            label_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            definition_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            externalDefinitionUrl_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            editorialNotes_ = s;
            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (created_ != null) {
              subBuilder = created_.toBuilder();
            }
            created_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(created_);
              created_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            createdBy_ = s;
            break;
          }
          case 82: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (modified_ != null) {
              subBuilder = modified_.toBuilder();
            }
            modified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modified_);
              modified_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            modifiedBy_ = s;
            break;
          }
          case 98: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (deleted_ != null) {
              subBuilder = deleted_.toBuilder();
            }
            deleted_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deleted_);
              deleted_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Vocabulary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gbif.vocabulary.grpc.Vocabulary.class, org.gbif.vocabulary.grpc.Vocabulary.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private int key_;
  /**
   * <code>int32 key = 1;</code>
   */
  public int getKey() {
    return key_;
  }

  public static final int NAMESPACE_FIELD_NUMBER = 2;
  private volatile java.lang.Object namespace_;
  /**
   * <code>string namespace = 2;</code>
   */
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <code>string namespace = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 4;
  private volatile java.lang.Object label_;
  /**
   * <code>string label = 4;</code>
   */
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <code>string label = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFINITION_FIELD_NUMBER = 5;
  private volatile java.lang.Object definition_;
  /**
   * <code>string definition = 5;</code>
   */
  public java.lang.String getDefinition() {
    java.lang.Object ref = definition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      definition_ = s;
      return s;
    }
  }
  /**
   * <code>string definition = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDefinitionBytes() {
    java.lang.Object ref = definition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      definition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTERNAL_DEFINITION_URL_FIELD_NUMBER = 6;
  private volatile java.lang.Object externalDefinitionUrl_;
  /**
   * <code>string external_definition_url = 6;</code>
   */
  public java.lang.String getExternalDefinitionUrl() {
    java.lang.Object ref = externalDefinitionUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalDefinitionUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string external_definition_url = 6;</code>
   */
  public com.google.protobuf.ByteString
      getExternalDefinitionUrlBytes() {
    java.lang.Object ref = externalDefinitionUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalDefinitionUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EDITORIAL_NOTES_FIELD_NUMBER = 7;
  private volatile java.lang.Object editorialNotes_;
  /**
   * <code>string editorial_notes = 7;</code>
   */
  public java.lang.String getEditorialNotes() {
    java.lang.Object ref = editorialNotes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      editorialNotes_ = s;
      return s;
    }
  }
  /**
   * <code>string editorial_notes = 7;</code>
   */
  public com.google.protobuf.ByteString
      getEditorialNotesBytes() {
    java.lang.Object ref = editorialNotes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      editorialNotes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp created_;
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public boolean hasCreated() {
    return created_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public com.google.protobuf.Timestamp getCreated() {
    return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
  }
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
    return getCreated();
  }

  public static final int CREATED_BY_FIELD_NUMBER = 9;
  private volatile java.lang.Object createdBy_;
  /**
   * <code>string created_by = 9;</code>
   */
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string created_by = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODIFIED_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp modified_;
  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  public boolean hasModified() {
    return modified_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  public com.google.protobuf.Timestamp getModified() {
    return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
  }
  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
    return getModified();
  }

  public static final int MODIFIED_BY_FIELD_NUMBER = 11;
  private volatile java.lang.Object modifiedBy_;
  /**
   * <code>string modified_by = 11;</code>
   */
  public java.lang.String getModifiedBy() {
    java.lang.Object ref = modifiedBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modifiedBy_ = s;
      return s;
    }
  }
  /**
   * <code>string modified_by = 11;</code>
   */
  public com.google.protobuf.ByteString
      getModifiedByBytes() {
    java.lang.Object ref = modifiedBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modifiedBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELETED_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp deleted_;
  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  public boolean hasDeleted() {
    return deleted_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  public com.google.protobuf.Timestamp getDeleted() {
    return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
  }
  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
    return getDeleted();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (key_ != 0) {
      output.writeInt32(1, key_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, namespace_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getLabelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, label_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, definition_);
    }
    if (!getExternalDefinitionUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, externalDefinitionUrl_);
    }
    if (!getEditorialNotesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, editorialNotes_);
    }
    if (created_ != null) {
      output.writeMessage(8, getCreated());
    }
    if (!getCreatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createdBy_);
    }
    if (modified_ != null) {
      output.writeMessage(10, getModified());
    }
    if (!getModifiedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, modifiedBy_);
    }
    if (deleted_ != null) {
      output.writeMessage(12, getDeleted());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (key_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, key_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, namespace_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getLabelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, label_);
    }
    if (!getDefinitionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, definition_);
    }
    if (!getExternalDefinitionUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, externalDefinitionUrl_);
    }
    if (!getEditorialNotesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, editorialNotes_);
    }
    if (created_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCreated());
    }
    if (!getCreatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createdBy_);
    }
    if (modified_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getModified());
    }
    if (!getModifiedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, modifiedBy_);
    }
    if (deleted_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getDeleted());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gbif.vocabulary.grpc.Vocabulary)) {
      return super.equals(obj);
    }
    org.gbif.vocabulary.grpc.Vocabulary other = (org.gbif.vocabulary.grpc.Vocabulary) obj;

    boolean result = true;
    result = result && (getKey()
        == other.getKey());
    result = result && getNamespace()
        .equals(other.getNamespace());
    result = result && getName()
        .equals(other.getName());
    result = result && getLabel()
        .equals(other.getLabel());
    result = result && getDefinition()
        .equals(other.getDefinition());
    result = result && getExternalDefinitionUrl()
        .equals(other.getExternalDefinitionUrl());
    result = result && getEditorialNotes()
        .equals(other.getEditorialNotes());
    result = result && (hasCreated() == other.hasCreated());
    if (hasCreated()) {
      result = result && getCreated()
          .equals(other.getCreated());
    }
    result = result && getCreatedBy()
        .equals(other.getCreatedBy());
    result = result && (hasModified() == other.hasModified());
    if (hasModified()) {
      result = result && getModified()
          .equals(other.getModified());
    }
    result = result && getModifiedBy()
        .equals(other.getModifiedBy());
    result = result && (hasDeleted() == other.hasDeleted());
    if (hasDeleted()) {
      result = result && getDeleted()
          .equals(other.getDeleted());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey();
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
    hash = (53 * hash) + getDefinition().hashCode();
    hash = (37 * hash) + EXTERNAL_DEFINITION_URL_FIELD_NUMBER;
    hash = (53 * hash) + getExternalDefinitionUrl().hashCode();
    hash = (37 * hash) + EDITORIAL_NOTES_FIELD_NUMBER;
    hash = (53 * hash) + getEditorialNotes().hashCode();
    if (hasCreated()) {
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getCreated().hashCode();
    }
    hash = (37 * hash) + CREATED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    if (hasModified()) {
      hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getModified().hashCode();
    }
    hash = (37 * hash) + MODIFIED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getModifiedBy().hashCode();
    if (hasDeleted()) {
      hash = (37 * hash) + DELETED_FIELD_NUMBER;
      hash = (53 * hash) + getDeleted().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gbif.vocabulary.grpc.Vocabulary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gbif.vocabulary.grpc.Vocabulary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.gbif.vocabulary.grpc.Vocabulary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.gbif.vocabulary.grpc.Vocabulary)
      org.gbif.vocabulary.grpc.VocabularyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Vocabulary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gbif.vocabulary.grpc.Vocabulary.class, org.gbif.vocabulary.grpc.Vocabulary.Builder.class);
    }

    // Construct using org.gbif.vocabulary.grpc.Vocabulary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      key_ = 0;

      namespace_ = "";

      name_ = "";

      label_ = "";

      definition_ = "";

      externalDefinitionUrl_ = "";

      editorialNotes_ = "";

      if (createdBuilder_ == null) {
        created_ = null;
      } else {
        created_ = null;
        createdBuilder_ = null;
      }
      createdBy_ = "";

      if (modifiedBuilder_ == null) {
        modified_ = null;
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }
      modifiedBy_ = "";

      if (deletedBuilder_ == null) {
        deleted_ = null;
      } else {
        deleted_ = null;
        deletedBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gbif.vocabulary.grpc.VocabularyOuterClass.internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor;
    }

    public org.gbif.vocabulary.grpc.Vocabulary getDefaultInstanceForType() {
      return org.gbif.vocabulary.grpc.Vocabulary.getDefaultInstance();
    }

    public org.gbif.vocabulary.grpc.Vocabulary build() {
      org.gbif.vocabulary.grpc.Vocabulary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.gbif.vocabulary.grpc.Vocabulary buildPartial() {
      org.gbif.vocabulary.grpc.Vocabulary result = new org.gbif.vocabulary.grpc.Vocabulary(this);
      result.key_ = key_;
      result.namespace_ = namespace_;
      result.name_ = name_;
      result.label_ = label_;
      result.definition_ = definition_;
      result.externalDefinitionUrl_ = externalDefinitionUrl_;
      result.editorialNotes_ = editorialNotes_;
      if (createdBuilder_ == null) {
        result.created_ = created_;
      } else {
        result.created_ = createdBuilder_.build();
      }
      result.createdBy_ = createdBy_;
      if (modifiedBuilder_ == null) {
        result.modified_ = modified_;
      } else {
        result.modified_ = modifiedBuilder_.build();
      }
      result.modifiedBy_ = modifiedBy_;
      if (deletedBuilder_ == null) {
        result.deleted_ = deleted_;
      } else {
        result.deleted_ = deletedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gbif.vocabulary.grpc.Vocabulary) {
        return mergeFrom((org.gbif.vocabulary.grpc.Vocabulary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gbif.vocabulary.grpc.Vocabulary other) {
      if (other == org.gbif.vocabulary.grpc.Vocabulary.getDefaultInstance()) return this;
      if (other.getKey() != 0) {
        setKey(other.getKey());
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (!other.getDefinition().isEmpty()) {
        definition_ = other.definition_;
        onChanged();
      }
      if (!other.getExternalDefinitionUrl().isEmpty()) {
        externalDefinitionUrl_ = other.externalDefinitionUrl_;
        onChanged();
      }
      if (!other.getEditorialNotes().isEmpty()) {
        editorialNotes_ = other.editorialNotes_;
        onChanged();
      }
      if (other.hasCreated()) {
        mergeCreated(other.getCreated());
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        onChanged();
      }
      if (other.hasModified()) {
        mergeModified(other.getModified());
      }
      if (!other.getModifiedBy().isEmpty()) {
        modifiedBy_ = other.modifiedBy_;
        onChanged();
      }
      if (other.hasDeleted()) {
        mergeDeleted(other.getDeleted());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.gbif.vocabulary.grpc.Vocabulary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.gbif.vocabulary.grpc.Vocabulary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int key_ ;
    /**
     * <code>int32 key = 1;</code>
     */
    public int getKey() {
      return key_;
    }
    /**
     * <code>int32 key = 1;</code>
     */
    public Builder setKey(int value) {
      
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 key = 1;</code>
     */
    public Builder clearKey() {
      
      key_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object namespace_ = "";
    /**
     * <code>string namespace = 2;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string namespace = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string namespace = 2;</code>
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      namespace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string namespace = 2;</code>
     */
    public Builder clearNamespace() {
      
      namespace_ = getDefaultInstance().getNamespace();
      onChanged();
      return this;
    }
    /**
     * <code>string namespace = 2;</code>
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      namespace_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <code>string label = 4;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string label = 4;</code>
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <code>string label = 4;</code>
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object definition_ = "";
    /**
     * <code>string definition = 5;</code>
     */
    public java.lang.String getDefinition() {
      java.lang.Object ref = definition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        definition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string definition = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDefinitionBytes() {
      java.lang.Object ref = definition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        definition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string definition = 5;</code>
     */
    public Builder setDefinition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      definition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string definition = 5;</code>
     */
    public Builder clearDefinition() {
      
      definition_ = getDefaultInstance().getDefinition();
      onChanged();
      return this;
    }
    /**
     * <code>string definition = 5;</code>
     */
    public Builder setDefinitionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      definition_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object externalDefinitionUrl_ = "";
    /**
     * <code>string external_definition_url = 6;</code>
     */
    public java.lang.String getExternalDefinitionUrl() {
      java.lang.Object ref = externalDefinitionUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalDefinitionUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string external_definition_url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExternalDefinitionUrlBytes() {
      java.lang.Object ref = externalDefinitionUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalDefinitionUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string external_definition_url = 6;</code>
     */
    public Builder setExternalDefinitionUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      externalDefinitionUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string external_definition_url = 6;</code>
     */
    public Builder clearExternalDefinitionUrl() {
      
      externalDefinitionUrl_ = getDefaultInstance().getExternalDefinitionUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string external_definition_url = 6;</code>
     */
    public Builder setExternalDefinitionUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      externalDefinitionUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object editorialNotes_ = "";
    /**
     * <code>string editorial_notes = 7;</code>
     */
    public java.lang.String getEditorialNotes() {
      java.lang.Object ref = editorialNotes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        editorialNotes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string editorial_notes = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEditorialNotesBytes() {
      java.lang.Object ref = editorialNotes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        editorialNotes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string editorial_notes = 7;</code>
     */
    public Builder setEditorialNotes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      editorialNotes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string editorial_notes = 7;</code>
     */
    public Builder clearEditorialNotes() {
      
      editorialNotes_ = getDefaultInstance().getEditorialNotes();
      onChanged();
      return this;
    }
    /**
     * <code>string editorial_notes = 7;</code>
     */
    public Builder setEditorialNotesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      editorialNotes_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp created_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public boolean hasCreated() {
      return createdBuilder_ != null || created_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.Timestamp getCreated() {
      if (createdBuilder_ == null) {
        return created_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      } else {
        return createdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder setCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        created_ = value;
        onChanged();
      } else {
        createdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder setCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdBuilder_ == null) {
        created_ = builderForValue.build();
        onChanged();
      } else {
        createdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder mergeCreated(com.google.protobuf.Timestamp value) {
      if (createdBuilder_ == null) {
        if (created_ != null) {
          created_ =
            com.google.protobuf.Timestamp.newBuilder(created_).mergeFrom(value).buildPartial();
        } else {
          created_ = value;
        }
        onChanged();
      } else {
        createdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public Builder clearCreated() {
      if (createdBuilder_ == null) {
        created_ = null;
        onChanged();
      } else {
        created_ = null;
        createdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedBuilder() {
      
      onChanged();
      return getCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder() {
      if (createdBuilder_ != null) {
        return createdBuilder_.getMessageOrBuilder();
      } else {
        return created_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : created_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedFieldBuilder() {
      if (createdBuilder_ == null) {
        createdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreated(),
                getParentForChildren(),
                isClean());
        created_ = null;
      }
      return createdBuilder_;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string created_by = 9;</code>
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_by = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_by = 9;</code>
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 9;</code>
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 9;</code>
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp modified_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public boolean hasModified() {
      return modifiedBuilder_ != null || modified_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public com.google.protobuf.Timestamp getModified() {
      if (modifiedBuilder_ == null) {
        return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      } else {
        return modifiedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public Builder setModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modified_ = value;
        onChanged();
      } else {
        modifiedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public Builder setModified(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedBuilder_ == null) {
        modified_ = builderForValue.build();
        onChanged();
      } else {
        modifiedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public Builder mergeModified(com.google.protobuf.Timestamp value) {
      if (modifiedBuilder_ == null) {
        if (modified_ != null) {
          modified_ =
            com.google.protobuf.Timestamp.newBuilder(modified_).mergeFrom(value).buildPartial();
        } else {
          modified_ = value;
        }
        onChanged();
      } else {
        modifiedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public Builder clearModified() {
      if (modifiedBuilder_ == null) {
        modified_ = null;
        onChanged();
      } else {
        modified_ = null;
        modifiedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getModifiedBuilder() {
      
      onChanged();
      return getModifiedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
      if (modifiedBuilder_ != null) {
        return modifiedBuilder_.getMessageOrBuilder();
      } else {
        return modified_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp modified = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getModifiedFieldBuilder() {
      if (modifiedBuilder_ == null) {
        modifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getModified(),
                getParentForChildren(),
                isClean());
        modified_ = null;
      }
      return modifiedBuilder_;
    }

    private java.lang.Object modifiedBy_ = "";
    /**
     * <code>string modified_by = 11;</code>
     */
    public java.lang.String getModifiedBy() {
      java.lang.Object ref = modifiedBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modifiedBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modified_by = 11;</code>
     */
    public com.google.protobuf.ByteString
        getModifiedByBytes() {
      java.lang.Object ref = modifiedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifiedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modified_by = 11;</code>
     */
    public Builder setModifiedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modifiedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string modified_by = 11;</code>
     */
    public Builder clearModifiedBy() {
      
      modifiedBy_ = getDefaultInstance().getModifiedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string modified_by = 11;</code>
     */
    public Builder setModifiedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modifiedBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp deleted_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public boolean hasDeleted() {
      return deletedBuilder_ != null || deleted_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public com.google.protobuf.Timestamp getDeleted() {
      if (deletedBuilder_ == null) {
        return deleted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
      } else {
        return deletedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public Builder setDeleted(com.google.protobuf.Timestamp value) {
      if (deletedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deleted_ = value;
        onChanged();
      } else {
        deletedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public Builder setDeleted(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deletedBuilder_ == null) {
        deleted_ = builderForValue.build();
        onChanged();
      } else {
        deletedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public Builder mergeDeleted(com.google.protobuf.Timestamp value) {
      if (deletedBuilder_ == null) {
        if (deleted_ != null) {
          deleted_ =
            com.google.protobuf.Timestamp.newBuilder(deleted_).mergeFrom(value).buildPartial();
        } else {
          deleted_ = value;
        }
        onChanged();
      } else {
        deletedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public Builder clearDeleted() {
      if (deletedBuilder_ == null) {
        deleted_ = null;
        onChanged();
      } else {
        deleted_ = null;
        deletedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeletedBuilder() {
      
      onChanged();
      return getDeletedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder() {
      if (deletedBuilder_ != null) {
        return deletedBuilder_.getMessageOrBuilder();
      } else {
        return deleted_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deleted_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp deleted = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDeletedFieldBuilder() {
      if (deletedBuilder_ == null) {
        deletedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeleted(),
                getParentForChildren(),
                isClean());
        deleted_ = null;
      }
      return deletedBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:org.gbif.vocabulary.grpc.Vocabulary)
  }

  // @@protoc_insertion_point(class_scope:org.gbif.vocabulary.grpc.Vocabulary)
  private static final org.gbif.vocabulary.grpc.Vocabulary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gbif.vocabulary.grpc.Vocabulary();
  }

  public static org.gbif.vocabulary.grpc.Vocabulary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vocabulary>
      PARSER = new com.google.protobuf.AbstractParser<Vocabulary>() {
    public Vocabulary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vocabulary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Vocabulary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vocabulary> getParserForType() {
    return PARSER;
  }

  public org.gbif.vocabulary.grpc.Vocabulary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

