// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

public interface VocabularyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.gbif.vocabulary.grpc.Vocabulary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 key = 1;</code>
   */
  int getKey();

  /**
   * <code>string namespace = 2;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string label = 4;</code>
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 4;</code>
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>string definition = 5;</code>
   */
  java.lang.String getDefinition();
  /**
   * <code>string definition = 5;</code>
   */
  com.google.protobuf.ByteString
      getDefinitionBytes();

  /**
   * <code>string external_definition_url = 6;</code>
   */
  java.lang.String getExternalDefinitionUrl();
  /**
   * <code>string external_definition_url = 6;</code>
   */
  com.google.protobuf.ByteString
      getExternalDefinitionUrlBytes();

  /**
   * <code>string editorial_notes = 7;</code>
   */
  java.lang.String getEditorialNotes();
  /**
   * <code>string editorial_notes = 7;</code>
   */
  com.google.protobuf.ByteString
      getEditorialNotesBytes();

  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  boolean hasCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  com.google.protobuf.Timestamp getCreated();
  /**
   * <code>.google.protobuf.Timestamp created = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedOrBuilder();

  /**
   * <code>string created_by = 9;</code>
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string created_by = 9;</code>
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  boolean hasModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  com.google.protobuf.Timestamp getModified();
  /**
   * <code>.google.protobuf.Timestamp modified = 10;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder();

  /**
   * <code>string modified_by = 11;</code>
   */
  java.lang.String getModifiedBy();
  /**
   * <code>string modified_by = 11;</code>
   */
  com.google.protobuf.ByteString
      getModifiedByBytes();

  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  boolean hasDeleted();
  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  com.google.protobuf.Timestamp getDeleted();
  /**
   * <code>.google.protobuf.Timestamp deleted = 12;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeletedOrBuilder();
}
