// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vocabulary.proto

package org.gbif.vocabulary.grpc;

public final class VocabularyOuterClass {
  private VocabularyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_VocabularyKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_VocabularyKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_Vocabulary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_Concept_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_Concept_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020vocabulary.proto\022\030org.gbif.vocabulary." +
      "grpc\032\037google/protobuf/timestamp.proto\"\034\n" +
      "\rVocabularyKey\022\013\n\003key\030\001 \001(\005\"\310\002\n\nVocabula" +
      "ry\022\013\n\003key\030\001 \001(\005\022\021\n\tnamespace\030\002 \001(\t\022\014\n\004na" +
      "me\030\003 \001(\t\022\r\n\005label\030\004 \001(\t\022\022\n\ndefinition\030\005 " +
      "\001(\t\022\037\n\027external_definition_url\030\006 \001(\t\022\027\n\017" +
      "editorial_notes\030\007 \001(\t\022+\n\007created\030\010 \001(\0132\032" +
      ".google.protobuf.Timestamp\022\022\n\ncreated_by" +
      "\030\t \001(\t\022,\n\010modified\030\n \001(\0132\032.google.protob" +
      "uf.Timestamp\022\023\n\013modified_by\030\013 \001(\t\022+\n\007del",
      "eted\030\014 \001(\0132\032.google.protobuf.Timestamp\"\316" +
      "\005\n\007Concept\022\026\n\016vocabulary_key\030\001 \001(\005\022\022\n\npa" +
      "rent_key\030\002 \001(\005\022\027\n\017replaced_by_key\030\003 \001(\005\022" +
      "\014\n\004name\030\004 \001(\t\022;\n\005label\030\005 \003(\0132,.org.gbif." +
      "vocabulary.grpc.Concept.LabelEntry\022R\n\021al" +
      "ternative_label\030\006 \003(\01327.org.gbif.vocabul" +
      "ary.grpc.Concept.AlternativeLabelEntry\022E" +
      "\n\ndefinition\030\007 \003(\01321.org.gbif.vocabulary" +
      ".grpc.Concept.DefinitionEntry\022\037\n\027externa" +
      "l_definition_url\030\010 \001(\t\022\023\n\013same_as_url\030\t ",
      "\003(\t\022\027\n\017editorial_notes\030\n \003(\t\022+\n\007created\030" +
      "\013 \001(\0132\032.google.protobuf.Timestamp\022\022\n\ncre" +
      "ated_by\030\014 \001(\t\022,\n\010modified\030\r \001(\0132\032.google" +
      ".protobuf.Timestamp\022\023\n\013modified_by\030\016 \001(\t" +
      "\022+\n\007deleted\030\017 \001(\0132\032.google.protobuf.Time" +
      "stamp\032,\n\nLabelEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\0327\n\025AlternativeLabelEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\0321\n\017Definiti" +
      "onEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\0012" +
      "o\n\021VocabularyService\022Z\n\010Concepts\022\'.org.g",
      "bif.vocabulary.grpc.VocabularyKey\032!.org." +
      "gbif.vocabulary.grpc.Concept\"\0000\001B\034\n\030org." +
      "gbif.vocabulary.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_org_gbif_vocabulary_grpc_VocabularyKey_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_gbif_vocabulary_grpc_VocabularyKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_VocabularyKey_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_gbif_vocabulary_grpc_Vocabulary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_Vocabulary_descriptor,
        new java.lang.String[] { "Key", "Namespace", "Name", "Label", "Definition", "ExternalDefinitionUrl", "EditorialNotes", "Created", "CreatedBy", "Modified", "ModifiedBy", "Deleted", });
    internal_static_org_gbif_vocabulary_grpc_Concept_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_gbif_vocabulary_grpc_Concept_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_Concept_descriptor,
        new java.lang.String[] { "VocabularyKey", "ParentKey", "ReplacedByKey", "Name", "Label", "AlternativeLabel", "Definition", "ExternalDefinitionUrl", "SameAsUrl", "EditorialNotes", "Created", "CreatedBy", "Modified", "ModifiedBy", "Deleted", });
    internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_descriptor =
      internal_static_org_gbif_vocabulary_grpc_Concept_descriptor.getNestedTypes().get(0);
    internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_Concept_LabelEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_descriptor =
      internal_static_org_gbif_vocabulary_grpc_Concept_descriptor.getNestedTypes().get(1);
    internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_Concept_AlternativeLabelEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_descriptor =
      internal_static_org_gbif_vocabulary_grpc_Concept_descriptor.getNestedTypes().get(2);
    internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gbif_vocabulary_grpc_Concept_DefinitionEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
